--- 
apiVersion: v1
kind: Service
metadata: 
  name: carts
  labels:
    keptn: "{{ .Values.keptn.service }}-{{ .Values.keptn.project }}-{{ .Values.keptn.stage }}"-canary
spec: 
  type: ClusterIP
  ports: 
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector: 
    app: carts
